## *Title*: -   [Low Reynold number with high energy flux by design alignment between stress by injection and background strain](https://www.leifang.org/)

#### **<font color="#4bacc6">From 2024.09.01--present</font>**

My recent program was relevant to observe the energy flux in different experiment condition,
however, with similar Reynolds number. Based on the latest research in our lab, 
we observed energy flux in turbulent flow can be manipulate by modify the coupling of the eigenvector of background shear flow
and stress which generated by Energy injection. We try to extend this work to low Reynolds number regime, 
which indicate that even extremely low Re number, can generate relative high energy flux.
